spring:
  application:
    name: Kafka-Manager
  cloud:
    config:
      username: user
      password: password.
  config:
    import: configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9091
    consumer.group-id: group1